### PR TITLE
Add search/query command to eva

### LINKED ISSUE #18: Implement search issues feature
We should have a feature which will allow the user to search issues containing a particular keyword from the metakgp orgsanisation.

`eva contribute [keyword]`

Requested by @athityakumar

### PR DESCRIPTION
**Pull request by thealphadollar**
- Refactored send_issues.coffee code to remove clutter and extra lines. Also, the code now displays 100 results per page.
- Now `@eva search [phrase]` fetches and shows the issues matching the keywords, in a fashion shown below.

Below is how the result looks; has been tested on "metakgp" organization.
Command: `eva search coding email`

screenshot from 2018-05-10 19-04-36

Two environment variables have been added to Heroku App to facilitate authentication for the Github API.
```
- HUBOT_GITHUB_TOKEN
- HUBOT_GITHUB_USER
```

It is NOT recommended to replace `HUBOT_GITHUB_TOKEN` with any other token unless generated by method listed [here ](https://github.com/iangreenleaf/githubot) under "Acquire a token".

**Change severity: high**
fixes #18

### CODE REVIEW

**Comment by thealphadollar** [comment]
@icyflame @athityakumar @amrav  Please review :D Once reviewed I will push it to heroku.

**Comment by icyflame** [comment]
@thealphadollar Thanks for the patch. Before I review this, the approach looks to be very resource intensive. 

**Fetching the issues each time:** this isn't required and it's very resource intensive. it's better to do one of two things:

  1. take the issues and index locally (say in ElasticSearch) and then run a full-text search through it each time (there are several variables here and it's very easy to use)
  1. send the query to GitHub and let them return <5 issues that match the query by default. APIv3 doesn't seem to have this feature (searching issues of an organization). I can't find it in v4 either, although I haven't looked thoroughly.

In the absence of option 2, we have to go with 1 and use an add-on like [this](https://devcenter.heroku.com/articles/foundelasticsearch).

**Comment by thealphadollar** [comment]
@icyflame  Updated

- Uses /search/issues method of the github API with organisation as metakgp.
- Remove the set env variables since authentication is not required by this method.
- Update documentation in the script.

screenshot from 2018-05-19 22-29-06

**change severity: moderate**

**Comment by icyflame** [comment]
Merged into master. Couple things that I fixed:

* Changed a few things to reduce the code. If you want to do the total_count thing, then you should use "switch-case" instead of these if-else statements which add so many unnecessary lines.
* Coffee script comments use hashes. Triple quoting isn't detected as comments in standard text editors and that's distracting.

**Pull request merged**
