### PR TITLE
Send link to join the metakgp-announcement google group to new users

### PR DESCRIPTION
**Pull request by DefCon-007**

### CODE REVIEW

**Comment by hargup** [comment]
+1

**Comment by icyflame** [comment]
Hey Ayush, this change is appreciated. We should concentrate on telling them more about MetaKGP though, before asking them to join a mailing list. Just saying, will merge this.

**Comment by icyflame** [comment]
@DefCon-007 Nice branch name :smile:

**Comment by athityakumar** [comment]
I saw the branch name just now! :smile: 

First Pikachu, and now Squirtle. :joy:

**Comment by DefCon-007** [comment]
😛

**Comment by DefCon-007** [comment]
Saving Mewtwo for the best PR 😛

**Comment by athityakumar** [comment]
Mewtwo or Mew or Arceus? I've 100s of branch names on my mind now. :wink:

**Pull request merged**
